import argparse
import shutil
import subprocess
import sys
import json
import logging
import os
import shlex
import stat
import textwrap
import time
from typing import List, Optional
import yaml

from compart.compart import Compart, AgentCompart, CompartConfig
from compart.compartments import Compartment, CompartmentConfig
from compart.hooks.base import SandboxRunner, diff_trees, index_workdir
from compart.sandbox.snapshot import SnapshotManager
from compart.engine.session import SessionManager, AgentSession, SessionStatus
from compart.engine.lane import LaneManager, Lane, LaneStatus
from compart.engine.integration import IntegrationEngine
from compart.engine.execution import Execution, ExecutionManager, ExecutionKind, ExecutionStatus
from compart.engine.pty_supervisor import PtySupervisor
from compart.config import (
    CompartmentConfig,
    WorkflowConfig,
    WorkflowNodeConfig,
    WorkspaceConfig,
    load_config,
    find_workspace_root,
    is_compart_workspace,
)

_logger = logging.getLogger("compart.cli")

COMPART_DIR = ".compart"
TOPOLOGY_FILE = os.path.join(COMPART_DIR, "topology.json")
CONFIG_FILE = os.path.join(COMPART_DIR, "config.yaml")

_KNOWN_AGENTS = ["claude", "codex", "opencode", "cursor", "aider"]

_AGENT_DISPLAY = {
    "claude": "Claude",
    "codex": "Codex",
    "opencode": "OpenCode",
    "cursor": "Cursor",
    "aider": "Aider",
}



def _print_json(data: dict):
    print(json.dumps(data, indent=2))


def _load_topology() -> dict:
    if not os.path.exists(TOPOLOGY_FILE):
        print(f"Error: Not a compart project (missing {TOPOLOGY_FILE}). Run 'compart init' first.")
        sys.exit(1)
    with open(TOPOLOGY_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def _save_topology(topo: dict):
    with open(TOPOLOGY_FILE, "w", encoding="utf-8") as f:
        json.dump(topo, f, indent=2)
        f.write("\n")



_SHIM_TEMPLATE = """\
#!/usr/bin/env bash
# Compart workspace shim for: {agent}
# Auto-generated by `compart init`. Do NOT edit by hand.
set -e

_COMPART_REAL="{real_path}"

_find_workspace() {{
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -d "$dir/.compart" ]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}}

_ws="$(_find_workspace 2>/dev/null || true)"

if [ -n "$_ws" ]; then
  if [ -n "${{COMPART_EXECUTION_ID:-}}" ]; then
    # Already inside a Compart execution (an agent launched another agent).
    # Inherit the parent execution's kernel boundary - do not wrap again.
    exec "$_COMPART_REAL" "$@"
  fi
  # Delegate to the Compart exec shim, which applies the compartment policy
  # and records the execution as an AgentSession.
  exec python3 -m compart._exec_shim "{agent}" "$_ws" "$@"
else
  # Outside a workspace - run the real binary transparently.
  exec "$_COMPART_REAL" "$@"
fi
"""

_CONFIG_YAML_TEMPLATE = """\
# Compart Workspace Configuration
# See https://github.com/Devaretanmay/Compart for docs.

compartments:
  default:
    filesystem: workspace     # read + write within workspace
    network: restricted       # block outbound network by default

  research:
    filesystem: read-only
    network: allowed

  builder:
    filesystem: read-write
    network: restricted

  network:
    filesystem: read-only
    network: allowed          # outbound network permitted (email, API calls)

  tester:
    filesystem: read-only
    network: restricted

agents:
  claude:
    compartment: default
  codex:
    compartment: default
  opencode:
    compartment: default

# Declared workflow DAGs - run with `compart workflow run <name>`.
# Each node executes as its own governed Execution in its own compartment;
# depends_on determines when nodes may run.
#
# workflows:
#   feature-development:
#     nodes:
#       research:
#         type: agent
#         command: opencode run --task "research the codebase"
#         compartment: research
#       build:
#         type: agent
#         command: claude -p "implement the feature"
#         compartment: default
#         depends_on: [research]
#       test:
#         type: process
#         command: pytest -q
#         compartment: tester
#         depends_on: [build]
"""


def _resolve_real_binary(agent_name: str, workspace_root: str) -> str | None:
    """Resolve the real agent binary, excluding Compart's own shim dir from PATH."""
    shim_dir = os.path.abspath(os.path.join(workspace_root, ".compart", "bin"))
    clean_path = os.pathsep.join(
        p for p in os.environ.get("PATH", "").split(os.pathsep)
        if p and os.path.abspath(p) != shim_dir
    )
    return shutil.which(agent_name, path=clean_path)


def _write_shims(compart_dir: str) -> list[str]:
    """Detect installed agents and write shim scripts into .compart/bin/."""
    bin_dir = os.path.join(compart_dir, "bin")
    os.makedirs(bin_dir, exist_ok=True)
    created = []
    for agent in _KNOWN_AGENTS:
        real = shutil.which(agent)
        if not real:
            continue
        shim_path = os.path.join(bin_dir, agent)
        with open(shim_path, "w", encoding="utf-8") as f:
            f.write(_SHIM_TEMPLATE.format(agent=agent, real_path=real))
        os.chmod(shim_path, os.stat(shim_path).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        created.append(agent)
    return created


def cmd_init(args):
    """Initialize a Compart workspace in the current directory."""
    for sub in ("state", "logs", "snapshots", "sessions", "lanes", "executions", "integration"):
        os.makedirs(os.path.join(COMPART_DIR, sub), exist_ok=True)

    if not os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            f.write(_CONFIG_YAML_TEMPLATE)

    if not os.path.exists(TOPOLOGY_FILE):
        project_name = os.path.basename(os.path.abspath("."))
        _save_topology({"name": project_name, "compartments": {}, "connections": []})

    created_shims = _write_shims(COMPART_DIR)

    project_name = os.path.basename(os.path.abspath("."))
    print(f"Initialized Compart workspace in {os.path.abspath(COMPART_DIR)}/\n")

    detected = []
    if shutil.which("git"):
        detected.append("Git")
    detected += [_AGENT_DISPLAY.get(a, a.capitalize()) for a in created_shims]
    if detected:
        print(f"Detected: {', '.join(detected)}")
        for a in created_shims:
            real = shutil.which(a)
            print(f"  {a:<12} -> {real}")
        print()

    cfg = load_config(CONFIG_FILE)
    default_comp = cfg.compartments.get("default")
    fs_label = getattr(default_comp, "filesystem", "workspace") if default_comp else "workspace"
    net_label = getattr(default_comp, "network", "restricted") if default_comp else "restricted"
    print(f"Default policy: {fs_label} filesystem | {net_label} network | protected credentials\n")
    print("Commands:")
    print("  Run an agent:      compart claude | opencode | codex")
    print("  Create a workflow: compart -w <name>")
    print("  Add steps:         compart step <name> <file_or_dir>")
    print("  Run workflow:      compart run <name>")


def cmd_status(args):
    """Show workspace status: running executions, lanes, security events."""
    ws_root = find_workspace_root()
    if not ws_root:
        print("Error: Not inside a Compart workspace. Run 'compart init' first.")
        sys.exit(1)

    project_name = os.path.basename(ws_root)
    cfg = load_config(os.path.join(ws_root, ".compart", "config.yaml"))
    exec_mgr = ExecutionManager(workdir=ws_root)
    lane_mgr = LaneManager(workdir=ws_root)
    sess_mgr = SessionManager(workdir=ws_root)

    running = exec_mgr.list_running()
    all_execs = exec_mgr.list_all()
    lanes = lane_mgr.list_lanes()
    sessions = sess_mgr.list_sessions()

    blocked = sum(
        1 for ex in all_execs
        for ev in ex.events
        if "blocked" in ev.get("name", "").lower() or "denied" in ev.get("name", "").lower()
    )

    print(f"\nCOMPART WORKSPACE: {project_name}\n")

    if running:
        print("AGENTS RUNNING")
        for ex in running:
            dur = f"{ex.duration_s:.0f}s" if ex.duration_s else "?"
            changes = len(ex.changes)
            print(f"  * {ex.agent_name:<12} {ex.compartment_id:<12} pid:{ex.pid or '?':<8} {changes} change(s)  ({dur})")
    else:
        print("AGENTS RUNNING\n  none")

    print()
    completed = [s for s in sessions if s.status == SessionStatus.COMPLETED][:3]
    if completed:
        print("RECENT SESSIONS")
        for s in completed:
            dur = round(((s.finished_at or 0) - (s.started_at or 0)), 1)
            print(f"  [OK] {s.agent:<12} lane:{s.lane_id:<12} {len(s.changes)} change(s)  ({dur}s)")
    else:
        print("RECENT SESSIONS\n  none")

    print()
    workflows = [ex for ex in all_execs if ex.kind == ExecutionKind.WORKFLOW][:5]
    if workflows:
        print("WORKFLOWS")
        for wf in workflows:
            dur = f"{wf.duration_s:.0f}s" if wf.duration_s else "?"
            name = wf.command[1] if len(wf.command) > 1 else (wf.command[0] if wf.command else "?")
            print(f"  # {wf.execution_id:<12} {name:<24} {wf.status:<12} {len(wf.changes)} change(s)  ({dur})")
    else:
        print("WORKFLOWS\n  none")

    print()
    if lanes:
        print("LANES")
        for l in lanes:
            print(f"  {l.lane_id:<14} {l.agent_id:<12} {l.status:<12} {len(l.changes)} file(s)")
    else:
        print("LANES\n  none")

    print()
    print("SECURITY")
    print(f"  {blocked} blocked action(s)")
    print(f"  0 credential escapes")
    print()


def _snapshot_worktree(workspace_root: str, snapshot_id: str) -> str:
    """Copy the current worktree into ``.compart/snapshots/<snapshot_id>/``.

    Taken before a governed execution runs so its changes can later be
    undone / rolled back / restored.  Returns the snapshot directory.
    """
    snap_dir = os.path.join(workspace_root, ".compart", "snapshots", snapshot_id)
    SnapshotManager(workdir=workspace_root, snapshot_dir=snap_dir).snapshot()
    return snap_dir


def _resolve_compartment(
    cfg: WorkspaceConfig,
    agent_name: str,
    override: Optional[str] = None,
) -> CompartmentConfig:
    """Resolve the compartment for an execution.

    An explicit override always wins; otherwise the agent's configured default
    compartment applies; otherwise the workspace default.  Agent defaults are
    convenience routing, never security identity - every execution carries its
    own resolved policy.
    """
    if override:
        comp = cfg.compartments.get(override)
        if comp is None:
            print(
                f"Error: Unknown compartment '{override}'. "
                f"Declared: {sorted(cfg.compartments)}"
            )
            sys.exit(1)
        return comp
    return cfg.compartment_for_agent(agent_name)


def _launch_agent(
    agent_name: str,
    workspace_root: str,
    user_argv: Optional[List[str]] = None,
    compartment_name: Optional[str] = None,
) -> int:
    """Launch an interactive agent as a governed Execution.

    Creates an Execution + AgentSession, applies the resolved compartment
    policy in the PTY child before the real binary runs, and records the
    outcome.  Returns the child returncode (exits 127 if the binary is
    missing).
    """
    cfg = load_config(os.path.join(workspace_root, ".compart", "config.yaml"))
    compartment = _resolve_compartment(cfg, agent_name, compartment_name)
    policy = {"permissions": compartment.permissions}
    user_argv = list(user_argv or [])
    command = [agent_name] + user_argv

    real_binary = _resolve_real_binary(agent_name, workspace_root)
    if real_binary is None:
        print(f"Error: Could not find agent binary: {agent_name}")
        sys.exit(127)

    extra_env: dict[str, str] = {}
    agent_cfg = cfg.agents.get(agent_name)
    if agent_cfg:
        extra_env.update(agent_cfg.extra_env)
    if agent_name == "opencode":
        xdg_base = os.path.join(workspace_root, ".compart", "xdg")
        for sub in ("config", "data", "cache", "state"):
            os.makedirs(os.path.join(xdg_base, sub), exist_ok=True)
        extra_env.update({
            "XDG_CONFIG_HOME": os.path.join(xdg_base, "config"),
            "XDG_DATA_HOME": os.path.join(xdg_base, "data"),
            "XDG_CACHE_HOME": os.path.join(xdg_base, "cache"),
            "XDG_STATE_HOME": os.path.join(xdg_base, "state"),
        })

    exec_mgr = ExecutionManager(workdir=workspace_root)
    sess_mgr = SessionManager(workdir=workspace_root)

    execution = exec_mgr.create(
        kind=ExecutionKind.INTERACTIVE,
        command=command,
        compartment_id=compartment.name,
        policy=policy,
        extra_env=extra_env,
    )
    session = sess_mgr.create_session(
        agent_name=agent_name,
        task=" ".join(user_argv) if user_argv else f"Interactive {agent_name} session",
        compartment_name=compartment.name,
        permissions=policy.get("permissions", []),
    )
    execution.session_id = session.session_id

    before = index_workdir(workspace_root)
    execution.snapshot_dir = _snapshot_worktree(workspace_root, execution.execution_id)
    session.create_checkpoint("pre-execution", snapshot_manifest=execution.snapshot_dir)

    execution.start()
    exec_mgr.save(execution)
    session.start()
    sess_mgr.save_session(session)

    extra_env["COMPART_EXECUTION_ID"] = execution.execution_id

    supervisor = PtySupervisor(
        workdir=workspace_root,
        compartment_policy=policy,
        extra_env=extra_env,
    )

    stdin_is_tty = sys.stdin is not None and sys.stdin.isatty()
    if stdin_is_tty:
        returncode = supervisor.attach([real_binary] + user_argv)
    else:
        result = supervisor.capture([real_binary] + user_argv)
        if result.stdout:
            print(result.stdout, end="")
        returncode = result.returncode

    changes = diff_trees(before, index_workdir(workspace_root))
    execution.complete(returncode=returncode, changes=changes)
    exec_mgr.save(execution)
    session.complete(returncode=returncode, diffs=changes)
    sess_mgr.save_session(session)
    return returncode


def cmd_exec_shim(args):
    """Internal: called by workspace shim scripts to launch an agent under Compart.

    Usage: compart _exec_shim <agent_name> <workspace_root> [argv...]
    """
    if len(args.shim_args) < 2:
        print("Error: _exec_shim requires <agent_name> <workspace_root> [argv...]")
        sys.exit(1)

    agent_name = args.shim_args[0]
    workspace_root = args.shim_args[1]
    user_argv = args.shim_args[2:]
    returncode = _launch_agent(agent_name, workspace_root, user_argv=user_argv)
    sys.exit(returncode)


def cmd_inspect(args):
    """Dump declarative topology and state of the current project."""
    ws_root = find_workspace_root() or os.path.abspath(".")
    cfg_path = os.path.join(ws_root, ".compart", "config.yaml")
    cfg = load_config(cfg_path) if os.path.exists(cfg_path) else None
    topology = _load_topology()
    project_name = topology.get("name") or os.path.basename(ws_root)

    if getattr(args, "json", False):
        data = {"name": project_name, "topology": topology}
        if cfg:
            data["config"] = {
                "compartments": {k: {"filesystem": v.filesystem, "network": v.network} for k, v in cfg.compartments.items()},
                "agents": {k: {"compartment": v.compartment} for k, v in cfg.agents.items()},
            }
        _print_json(data)
    else:
        print(f"Compart Workspace: {project_name}\n")
        print("COMPARTMENTS\n")
        if cfg and cfg.compartments:
            for name, c in cfg.compartments.items():
                print(f"{name}")
                print(f"  filesystem   {c.filesystem}")
                print(f"  network      {c.network}\n")
        elif topology.get("compartments"):
            for name, c in topology["compartments"].items():
                print(f"{name}")
                print(f"  permissions  {c.get('permissions', [])}\n")
        else:
            print("default\n  filesystem   workspace\n  network      restricted\n")


def cmd_compartment_create(args):
    """Define a new inner compartment in topology.json."""
    topology = _load_topology()
    comps = topology.setdefault("compartments", {})
    if args.name in comps:
        print(f"Error: Compartment '{args.name}' already declared.")
        sys.exit(1)
    comps[args.name] = {"permissions": ["fs_read"]}
    _save_topology(topology)
    print(f"Registered inner compartment '{args.name}'.")


def cmd_connect(args):
    """Establish a directional connection between two inner compartments."""
    topology = _load_topology()
    comps = topology.get("compartments", {})
    if args.source not in comps:
        print(f"Error: Source compartment '{args.source}' not declared.")
        sys.exit(1)
    if args.target not in comps:
        print(f"Error: Target compartment '{args.target}' not declared.")
        sys.exit(1)
    conns = topology.setdefault("connections", [])
    edge = [args.source, args.target]
    if edge not in conns:
        conns.append(edge)
    _save_topology(topology)
    print(f"Connected '{args.source}' -> '{args.target}'.")


def cmd_run(args):
    """Run a workflow or materialize declared topology."""
    target = getattr(args, "target", None)
    if target:
        class _WfArgs:
            workflow = target
            compartment = getattr(args, "compartment", "default") or "default"
            verbose = getattr(args, "verbose", False)
        cmd_workflow_run(_WfArgs())
        return

    ws_root = find_workspace_root() or os.path.abspath(".")
    cfg = load_config(os.path.join(ws_root, ".compart", "config.yaml"))
    if cfg.workflows:
        print("Available Workflows:")
        for wname in sorted(cfg.workflows):
            print(f"  - {wname:<24} (run with: compart run {wname})")
        return

    if os.path.exists(TOPOLOGY_FILE):
        topology = _load_topology()
        comps = topology.get("compartments", {})
        if comps:
            print(f"Materializing declared topology for '{topology.get('name', 'unnamed')}'...")
            compart = AgentCompart(workdir=ws_root, verbose=True)
            for name, cfg_comp in comps.items():
                perms = cfg_comp.get("permissions", ["fs_read"])
                def dummy_fn(ctx, n=name):
                    print(f"[{n}] Executing inside kernel sandbox...")
                    return {"status": "ok"}
                compart.add(Compartment(name=name, fn=dummy_fn, config=CompartmentConfig(permissions=perms)))
            for edge in topology.get("connections", []):
                if isinstance(edge, (list, tuple)) and len(edge) >= 2:
                    compart.edge(edge[0], edge[1])
            result = compart.run()
            if result.status == "error":
                print(f"\nExecution failed: {result.errors}")
                sys.exit(1)
            else:
                print("\nExecution succeeded.")
            return

    print("No workflow specified. Usage: compart run <workflow_name>")


def cmd_exec(args):
    """Run a command or launch an agent inside an explicitly selected compartment."""
    if not args.cmd:
        print("Error: No command provided to exec. Usage: compart exec [--compartment X] <command>")
        sys.exit(1)

    ws_root = find_workspace_root() or os.path.abspath(".")
    cfg = load_config(os.path.join(ws_root, ".compart", "config.yaml"))
    cmd = list(args.cmd)

    if cmd[0] in _KNOWN_AGENTS:
        returncode = _launch_agent(
            cmd[0], ws_root, user_argv=cmd[1:], compartment_name=args.compartment,
        )
        sys.exit(returncode)

    compartment = _resolve_compartment(cfg, cmd[0], args.compartment)
    policy = {"permissions": compartment.permissions}
    cmd_str = shlex.join(cmd)
    print(f"Executing: {cmd_str}  (compartment: {compartment.name})")

    runner = SandboxRunner(
        workdir=ws_root,
        verbose=True,
        block_network="network" not in compartment.permissions,
    )
    exec_mgr = ExecutionManager(workdir=ws_root)
    execution = exec_mgr.create(
        kind=ExecutionKind.PROCESS,
        command=cmd,
        compartment_id=compartment.name,
        policy=policy,
    )
    execution.snapshot_dir = _snapshot_worktree(ws_root, execution.execution_id)
    execution.start()
    exec_mgr.save(execution)

    result = runner.run(
        cmd_str,
        permissions=compartment.permissions,
        env={"COMPART_EXECUTION_ID": execution.execution_id},
    )
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)
    if result.error:
        print(f"\nSandbox error: {result.error}", file=sys.stderr)

    execution.complete(returncode=result.returncode, changes=result.diffs)
    exec_mgr.save(execution)

    if result.returncode != 0:
        print(f"\nExecution failed with code {result.returncode}")
        sys.exit(result.returncode)
    print("\nExecution succeeded.")


def cmd_wrap(args):
    """Transparently govern any CLI agent command in a managed AgentSession & Virtual Lane under kernel isolation."""
    ws_root = find_workspace_root() or os.path.abspath(".")
    agent_name = args.agent or "Claude Code"
    task = args.task
    cmd_str = ""
    env_vars = {}

    if args.claude is not None:
        agent_name = "Claude Code"
        raw_task = args.claude.strip()
        if raw_task.startswith("[") and raw_task.endswith("]"):
            raw_task = raw_task[1:-1].strip()
        task = raw_task or task or "Claude Code Execution Task"
        if not args.cmd:
            cmd_str = f"claude -p {shlex.quote(task)}"

    elif getattr(args, "opencode", None) is not None:
        agent_name = "OpenCode"
        raw_task = args.opencode.strip()
        if raw_task.startswith("[") and raw_task.endswith("]"):
            raw_task = raw_task[1:-1].strip()
        task = raw_task or task or "OpenCode Execution Task"
        xdg_base = os.path.join(ws_root, ".compart", "xdg")
        for sub in ["config", "data", "cache", "state"]:
            os.makedirs(os.path.join(xdg_base, sub), exist_ok=True)
        env_vars.update({
            "XDG_CONFIG_HOME": os.path.join(xdg_base, "config"),
            "XDG_DATA_HOME": os.path.join(xdg_base, "data"),
            "XDG_CACHE_HOME": os.path.join(xdg_base, "cache"),
            "XDG_STATE_HOME": os.path.join(xdg_base, "state"),
        })
        if not args.cmd:
            cmd_str = f"opencode run {shlex.quote(task)}" if task else "opencode --help"

    if not cmd_str and args.cmd:
        cmd_str = shlex.join(args.cmd)
        if not task:
            task = cmd_str

    if not cmd_str:
        print("Error: No command or task provided to wrap.")
        sys.exit(1)

    lane_id = getattr(args, "lane", "default") or "default"
    lane_mgr = LaneManager(workdir=ws_root)
    lane = lane_mgr.get_lane(lane_id)
    if not lane:
        lane = lane_mgr.create_lane(name=lane_id, agent_id=agent_name)

    session_mgr = SessionManager(workdir=ws_root)
    exec_mgr = ExecutionManager(workdir=ws_root)
    session = session_mgr.create_session(
        agent_name=agent_name,
        task=task,
        compartment_name=f"Compartment_{lane_id}",
        permissions=["fs_read", "fs_write", "fs_exec"],
        lane_id=lane_id,
    )

    kind = ExecutionKind.INTERACTIVE if agent_name in ("Claude Code", "OpenCode") else ExecutionKind.PROCESS
    execution = exec_mgr.create(
        kind=kind,
        command=shlex.split(cmd_str),
        compartment_id=f"Compartment_{lane_id}",
        policy={"permissions": ["fs_read", "fs_write", "fs_exec"]},
    )
    execution.session_id = session.session_id
    execution.snapshot_dir = _snapshot_worktree(ws_root, execution.execution_id)
    session.create_checkpoint("pre-execution", snapshot_manifest=execution.snapshot_dir)
    execution.start()
    exec_mgr.save(execution)
    session.start()
    session_mgr.save_session(session)

    lane.session_id = session.session_id
    lane.status = LaneStatus.ACTIVE
    lane_mgr.save_lane(lane)

    env_vars["COMPART_EXECUTION_ID"] = execution.execution_id

    print(f"Compart Agent Session #{session.session_id} active on Virtual Agent Lane '{lane_id}'.")
    print(f"Governing agent command under kernel sandbox: {cmd_str}")

    runner = SandboxRunner(workdir=ws_root, verbose=args.verbose)
    result = runner.run(
        cmd_str,
        permissions=["fs_read", "fs_write", "fs_exec"],
        env=env_vars,
    )

    if result.stdout:
        print("\n--- Agent Output ---")
        print(result.stdout)
        print("--------------------")
    if result.error:
        print(f"\nSandbox error: {result.error}", file=sys.stderr)

    execution.complete(returncode=result.returncode, changes=result.diffs)
    exec_mgr.save(execution)
    session.log_action("EXECUTE", cmd_str, status="OK" if result.success else "FAILED", details=f"returncode={result.returncode}")
    session.complete(returncode=result.returncode, diffs=result.diffs)
    session_mgr.save_session(session)
    lane_mgr.record_diff(lane_id, result.diffs)
    print("\n" + session.format_ascii_view())


def cmd_lane_create(args):
    ws_root = find_workspace_root() or os.path.abspath(".")
    lane_mgr = LaneManager(workdir=ws_root)
    lane = lane_mgr.create_lane(name=args.name, agent_id=args.agent)
    print(f"Created Virtual Agent Lane '{lane.lane_id}' (Agent: {lane.agent_id}, Status: {lane.status}).")


def cmd_lanes(args):
    ws_root = find_workspace_root() or os.path.abspath(".")
    lane_mgr = LaneManager(workdir=ws_root)
    lanes = lane_mgr.list_lanes()
    if not lanes:
        print("No virtual agent lanes found. Run 'compart lane create <name>' or 'compart wrap --lane <name>' first.")
        return
    print(f"Virtual Agent Lanes ({len(lanes)}):")
    for l in lanes:
        print(f"  - [{l.lane_id}] Agent: {l.agent_id:<12} | Status: {l.status:<10} | Changes: {len(l.changes)} file(s)")


def cmd_lane_inspect(args):
    ws_root = find_workspace_root() or os.path.abspath(".")
    lane_mgr = LaneManager(workdir=ws_root)
    lane = lane_mgr.get_lane(args.name)
    if not lane:
        print(f"Error: Lane '{args.name}' not found.")
        sys.exit(1)
    if args.json:
        _print_json(lane.to_dict())
    else:
        print(f"================================================================")
        print(f"              COMPART VIRTUAL AGENT LANE #{lane.lane_id}        ")
        print(f"================================================================")
        print(f"Lane Name   : {lane.name}")
        print(f"Agent       : {lane.agent_id}")
        print(f"Status      : {lane.status}")
        print(f"Session ID  : {lane.session_id or 'None'}")
        print(f"Permissions : {lane.permissions}")
        print(f"----------------------------------------------------------------")
        print(f"Changes ({len(lane.changes)} file(s)):")
        if not lane.changes:
            print("  (No changes recorded)")
        else:
            for chg in lane.changes:
                print(f"  {chg.get('status', 'modified').upper()}: {chg.get('path', '')}")
        print(f"================================================================")


def cmd_integrate(args):
    ws_root = find_workspace_root() or os.path.abspath(".")
    eng = IntegrationEngine(workdir=ws_root)
    if args.subcommand == "create":
        cand = eng.create_candidate(args.lanes)
        print(f"Created Integration Candidate #{cand.candidate_id} combining lanes {cand.source_lanes}.")
        print(eng.preview())
    elif args.subcommand == "preview":
        print(eng.preview())
    elif args.subcommand == "apply":
        if eng.apply():
            print("Successfully applied integration candidate to workspace.")
        else:
            print("Failed to apply integration candidate.")


def cmd_sessions(args):
    ws_root = find_workspace_root() or os.path.abspath(".")
    mgr = SessionManager(workdir=ws_root)
    sessions = mgr.list_sessions()
    if not sessions:
        print("No recorded agent sessions found. Run 'compart wrap' or 'compart run' first.")
        return
    print(f"Recorded Agent Sessions ({len(sessions)}):")
    for s in sessions:
        duration = round((s.finished_at or time.time()) - s.started_at, 2)
        print(f"  - [{s.session_id}] {s.agent:<12} | Lane: {s.lane_id:<10} | Task: '{s.task}' | Status: {s.status:<10} ({duration}s)")


def cmd_session_inspect(args):
    ws_root = find_workspace_root() or os.path.abspath(".")
    mgr = SessionManager(workdir=ws_root)
    session = mgr.get_session(args.session_id)
    if not session:
        print(f"Error: Session '{args.session_id}' not found.")
        sys.exit(1)
    if args.json:
        _print_json(session.to_dict())
    else:
        print(session.format_ascii_view())


def cmd_session_rollback(args):
    ws_root = find_workspace_root() or os.path.abspath(".")
    mgr = SessionManager(workdir=ws_root)
    success = mgr.rollback_session(args.session_id)
    if success:
        print(f"Workspace successfully rolled back to state prior to Session #{args.session_id}.")
    else:
        print(f"Error: Failed to roll back Session #{args.session_id}.")
        sys.exit(1)


_NODE_KIND_BY_TYPE = {
    "agent": ExecutionKind.INTERACTIVE,
    "process": ExecutionKind.PROCESS,
    "service": ExecutionKind.SERVICE,
}


def _topo_sort(nodes: List[WorkflowNodeConfig]) -> List[WorkflowNodeConfig]:
    """Return nodes in dependency order; raise ValueError on cycles."""
    by_name = {n.name: n for n in nodes}
    visited: dict[str, int] = {}  # 0=unvisited, 1=in-progress, 2=done
    order: List[WorkflowNodeConfig] = []

    def visit(n: WorkflowNodeConfig) -> None:
        state = visited.get(n.name, 0)
        if state == 1:
            raise ValueError(f"Workflow cycle detected at node '{n.name}'")
        if state == 2:
            return
        visited[n.name] = 1
        for dep in n.depends_on:
            if dep in by_name:
                visit(by_name[dep])
            else:
                print(f"Warning: node '{n.name}' depends on unknown node '{dep}' - ignored.")
        visited[n.name] = 2
        order.append(n)

    for n in nodes:
        visit(n)
    return order


def _run_declared_workflow(ws_root: str, wf: WorkflowConfig, cfg: WorkspaceConfig) -> None:
    """Execute a declared YAML workflow DAG; each node is its own Execution."""
    try:
        nodes = _topo_sort(wf.nodes)
    except ValueError as exc:
        print(f"Error: {exc}")
        sys.exit(1)

    _STANDARD_COMPARTMENTS = {
        "research":  CompartmentConfig(name="research",  permissions=["fs_read", "fs_exec", "network"],          filesystem="read-only",  network="allowed"),
        "builder":   CompartmentConfig(name="builder",   permissions=["fs_read", "fs_write", "fs_exec"],         filesystem="read-write", network="restricted"),
        "network":   CompartmentConfig(name="network",   permissions=["fs_read", "fs_exec", "network"],          filesystem="read-only",  network="allowed"),
        "tester":    CompartmentConfig(name="tester",    permissions=["fs_read", "fs_exec"],                     filesystem="read-only",  network="restricted"),
    }
    for n in nodes:
        if n.compartment not in cfg.compartments:
            if n.compartment in _STANDARD_COMPARTMENTS:
                cfg.compartments[n.compartment] = _STANDARD_COMPARTMENTS[n.compartment]
            else:
                print(
                    f"Error: Workflow '{wf.name}' node '{n.name}' uses unknown compartment "
                    f"'{n.compartment}'. Declared: {sorted(cfg.compartments)}"
                )
                sys.exit(1)

    exec_mgr = ExecutionManager(workdir=ws_root)
    print(f"\nCOMPART WORKFLOW: {wf.name}  ({len(nodes)} node(s))\n")
    for n in nodes:
        print(f"  {n.name:<16} {n.type:<9} {n.compartment:<12} depends_on={n.depends_on}")
    print()

    executions: dict[str, Execution] = {}
    for n in nodes:
        executions[n.name] = exec_mgr.create(
            kind=_NODE_KIND_BY_TYPE.get(n.type, ExecutionKind.PROCESS),
            command=shlex.split(n.command) if n.command else [n.name],
            compartment_id=n.compartment,
            policy={"permissions": cfg.compartments[n.compartment].permissions},
        )

    failed: set[str] = set()
    for n in nodes:
        ex = executions[n.name]
        if any(d in failed for d in n.depends_on):
            ex.status = ExecutionStatus.SKIPPED
            ex.emit("execution.skipped", {"reason": "dependency failed"})
            exec_mgr.save(ex)
            print(f"  [SKIP] {n.name:<16} SKIPPED (dependency failed)")
            continue

        comp = cfg.compartments[n.compartment]
        ex.snapshot_dir = _snapshot_worktree(ws_root, ex.execution_id)
        ex.start()
        exec_mgr.save(ex)
        print(f"  [RUN]  {n.name:<16} running in '{n.compartment}' ...")

        runner = SandboxRunner(
            workdir=ws_root,
            verbose=False,
            block_network="network" not in comp.permissions,
        )
        try:
            node_cmd = n.command or n.name
            node_argv = shlex.split(node_cmd)
        except ValueError as exc:
            print(f"  [FAIL] {n.name:<16} FAILED (bad command string: {exc})")
            failed.add(n.name)
            ex.status = ExecutionStatus.FAILED
            exec_mgr.save(ex)
            continue
        result = runner.run(
            shlex.join(node_argv),
            permissions=comp.permissions,
            env={"COMPART_EXECUTION_ID": ex.execution_id},
        )
        if result.stdout:
            for line in result.stdout.splitlines():
                print(f"      {line}")
        if result.stderr and result.returncode != 0:
            for line in result.stderr.splitlines():
                print(f"      {line}", file=sys.stderr)
        if result.error:
            print(f"      Sandbox error: {result.error}", file=sys.stderr)

        ex.complete(returncode=result.returncode, changes=result.diffs)
        exec_mgr.save(ex)
        if result.returncode != 0:
            failed.add(n.name)
            print(f"  [FAIL] {n.name:<16} FAILED (exit {result.returncode})")
        else:
            print(f"  [OK]   {n.name:<16} completed ({len(result.diffs)} change(s))")

    completed = sum(1 for n in nodes if executions[n.name].status == ExecutionStatus.COMPLETED)
    skipped = sum(1 for n in nodes if executions[n.name].status == ExecutionStatus.SKIPPED)
    print(f"\nWorkflow '{wf.name}' finished: {completed} completed, {len(failed)} failed, {skipped} skipped.")
    sys.exit(0 if not failed else 1)


def _run_workflow_file(ws_root: str, workflow_file: str, compartment_id: str, verbose: bool) -> None:
    """Run a standalone workflow file (LangGraph, CrewAI, Python script) as one managed Execution."""
    if not os.path.exists(workflow_file):
        print(f"Error: Workflow file not found: {workflow_file}")
        sys.exit(1)

    cfg = load_config(os.path.join(ws_root, ".compart", "config.yaml"))
    policy = {}
    if compartment_id in cfg.compartments:
        policy = {"permissions": cfg.compartments[compartment_id].permissions}
    else:
        policy = {"permissions": ["fs_read", "fs_write", "fs_exec"]}

    exec_mgr = ExecutionManager(workdir=ws_root)
    sess_mgr = SessionManager(workdir=ws_root)
    execution = exec_mgr.create(
        kind=ExecutionKind.WORKFLOW,
        command=["python3", workflow_file],
        compartment_id=compartment_id,
        policy=policy,
    )
    session = sess_mgr.create_session(
        agent_name=workflow_file,
        task=f"Run workflow {workflow_file}",
        compartment_name=compartment_id,
        permissions=policy.get("permissions", []),
    )
    execution.session_id = session.session_id
    execution.snapshot_dir = _snapshot_worktree(ws_root, execution.execution_id)
    session.create_checkpoint("pre-execution", snapshot_manifest=execution.snapshot_dir)
    execution.start()
    exec_mgr.save(execution)
    session.start()
    sess_mgr.save_session(session)

    print(f"Compart Workflow Execution #{execution.execution_id}")
    print(f"Running: python3 {workflow_file} (compartment: {compartment_id})")

    runner = SandboxRunner(workdir=ws_root, verbose=verbose)
    result = runner.run(
        f"python3 {shlex.quote(workflow_file)}",
        permissions=policy.get("permissions", ["fs_read", "fs_exec"]),
    )
    if result.stdout:
        print(result.stdout)
    if result.stderr and not result.success:
        print(result.stderr, file=sys.stderr)

    execution.complete(returncode=result.returncode, changes=result.diffs)
    exec_mgr.save(execution)
    session.complete(returncode=result.returncode, diffs=result.diffs)
    sess_mgr.save_session(session)

    status_str = "[DONE]" if result.success else "[FAILED]"
    print(f"\n{status_str} (exit {result.returncode}) - {len(result.diffs)} file change(s)")
    sys.exit(0 if result.success else result.returncode)


def _infer_step_properties(
    target: str,
    name_opt: Optional[str] = None,
    comp_opt: Optional[str] = None,
    type_opt: Optional[str] = None,
) -> tuple[str, str, str, str]:
    """Auto-infer (step_name, command, step_type, compartment) from a file or command string."""
    target_clean = target.strip()
    is_file = os.path.exists(target_clean) or target_clean.endswith((".py", ".sh", ".js", ".ts", ".rb"))

    if is_file:
        base = os.path.splitext(os.path.basename(target_clean))[0]
        step_name = name_opt or base.replace("_", "-")
        py_bin = "python3" if shutil.which("python3") else "python"
        runners = {".py": f"{py_bin} {target_clean}", ".sh": f"bash {target_clean}", ".js": f"node {target_clean}", ".ts": f"node {target_clean}"}
        command = runners.get(os.path.splitext(target_clean)[1], target_clean)
        is_agent = any(k in target_clean.lower() for k in ["agent", "claude", "crewai", "langchain", "llm", "rag", "gpt", "prompt"])
        step_type = type_opt or ("agent" if is_agent else "process")
    else:
        first_word = target_clean.split()[0] if target_clean else "step"
        step_name = name_opt or os.path.basename(first_word).replace("_", "-")
        command = target_clean
        is_agent = any(k in target_clean.lower() for k in ["claude", "opencode", "codex", "agent", "crewai", "langchain"])
        step_type = type_opt or ("agent" if is_agent else "process")

    if comp_opt:
        compartment = comp_opt
    else:
        tc = target_clean.lower()
        comp_map = {
            "research": ["ocr", "scrape", "extract", "read", "audit", "search", "scan"],
            "builder": ["build", "patch", "rag", "excel", "write", "generate", "code"],
            "network": ["email", "send", "fetch", "api", "download", "http", "notify", "curl"],
            "tester": ["test", "verify", "check", "pytest"],
        }
        compartment = next((c for c, keywords in comp_map.items() if any(k in tc for k in keywords)), "default")

    return step_name, command, step_type, compartment


def cmd_workflow_branch(args):
    """Create a new workflow branch in workflows/<name>.yaml (Git-branch style)."""
    ws_root = find_workspace_root() or os.path.abspath(".")
    name = getattr(args, "name", "").strip()
    if not name:
        print("Error: Workflow branch name required. Usage: compart workflow branch <name>")
        sys.exit(1)

    wf_dir = os.path.join(ws_root, "workflows")
    os.makedirs(wf_dir, exist_ok=True)
    wf_path = os.path.join(wf_dir, f"{name}.yaml")

    if os.path.exists(wf_path):
        print(f"Workflow branch '{name}' already exists: workflows/{name}.yaml")
        return

    content = textwrap.dedent(f"""\
        # Compart Workflow Branch: {name}
        name: {name}
        description: "Agentic workflow {name}"

        steps: []
    """)

    with open(wf_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Created workflow branch: workflows/{name}.yaml")
    print(f"  To add steps:  compart step {name} <file_or_command>")
    print(f"  To execute:    compart workflow run {name}")


def cmd_workflow_show(args):
    """Inspect and visualize declared steps in a workflow branch."""
    ws_root = find_workspace_root() or os.path.abspath(".")
    cfg_path = os.path.join(ws_root, ".compart", "config.yaml")
    cfg = load_config(cfg_path) if os.path.exists(cfg_path) else None
    name = getattr(args, "name", None)
    if not name:
        wfs = sorted(cfg.workflows.keys()) if cfg and cfg.workflows else []
        print(f"Declared Workflows ({len(wfs)}):")
        for w in wfs:
            node_count = len(cfg.workflows[w].nodes)
            print(f"  - {w:<20} ({node_count} node(s))")
        return

    if cfg and name in cfg.workflows:
        wf = cfg.workflows[name]
        print(f"Workflow: {name}\n")
        nodes_list = wf.nodes if isinstance(wf.nodes, list) else list(wf.nodes.values())
        for i, node in enumerate(nodes_list):
            name_str = node.name.capitalize()
            print(f"  [{node.compartment}] {name_str}")
            if i < len(nodes_list) - 1:
                print("       │")
                print("       ▼")
        print()
    else:
        print(f"Error: Workflow '{name}' not found.")


def cmd_step(args):
    """Add step(s) to a workflow branch with smart auto-inferred properties."""
    ws_root = find_workspace_root() or os.path.abspath(".")
    wf_name = args.workflow.strip()
    target = args.target.strip()

    wf_dir = os.path.join(ws_root, "workflows")
    wf_path = os.path.join(wf_dir, f"{wf_name}.yaml")
    if not os.path.exists(wf_path):
        alt_path = os.path.join(wf_dir, f"{wf_name}.yml")
        if os.path.exists(alt_path):
            wf_path = alt_path
        else:
            os.makedirs(wf_dir, exist_ok=True)
            with open(wf_path, "w", encoding="utf-8") as f:
                f.write(f"name: {wf_name}\nsteps: []\n")
            print(f"Initialized new workflow file: workflows/{wf_name}.yaml")

    with open(wf_path, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}

    if "steps" not in data or not isinstance(data["steps"], list):
        data["steps"] = []

    candidates = []
    if os.path.isdir(target):
        for root_dir, _, filenames in os.walk(target):
            for fname in sorted(filenames):
                if fname.endswith((".py", ".sh", ".js", ".ts", ".rb")) and not fname.startswith("."):
                    candidates.append(os.path.join(root_dir, fname))
        if not candidates:
            print(f"No code scripts found in directory: {target}")
            return
    else:
        candidates = [target]

    added_count = 0
    is_interactive = sys.stdin is not None and sys.stdin.isatty() and len(candidates) > 1

    for cand in candidates:
        step_name, command, step_type, compartment = _infer_step_properties(
            cand,
            name_opt=getattr(args, "name", None) if len(candidates) == 1 else None,
            comp_opt=getattr(args, "compartment", None) if len(candidates) == 1 else None,
            type_opt=getattr(args, "type", None) if len(candidates) == 1 else None,
        )

        if is_interactive:
            print(f"\nFound file: {cand}")
            print(f"  Proposed step: '{step_name}' [type: {step_type}, compartment: {compartment}]")
            try:
                choice = input("  Press [Enter] to add, 's' to skip, or type 'name:compartment': ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\nAborted.")
                break
            if choice.lower() in ("s", "skip"):
                print(f"  Skipped {cand}.")
                continue
            if ":" in choice:
                parts = choice.split(":", 1)
                if parts[0].strip():
                    step_name = parts[0].strip()
                if parts[1].strip():
                    compartment = parts[1].strip()

        depends_on = getattr(args, "depends_on", None)
        if depends_on and len(candidates) == 1:
            deps = [d.strip() for d in depends_on.split(",") if d.strip()]
        elif data["steps"]:
            prev_name = data["steps"][-1].get("name")
            deps = [prev_name] if prev_name else []
        else:
            deps = []

        new_step = {
            "name": step_name,
            "type": step_type,
            "command": command,
            "compartment": compartment,
        }
        if deps:
            new_step["depends_on"] = deps

        data["steps"].append(new_step)
        added_count += 1
        print(f"[OK] Added step '{step_name}' [type: {step_type}, compartment: {compartment}]")
        print(f"  Command:    {command}")
        print(f"  Depends on: {deps or 'none (runs first)'}")

    with open(wf_path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, sort_keys=False)

    print(f"\nUpdated workflows/{os.path.basename(wf_path)} ({added_count} step(s) added).")


def cmd_workflow_run(args):
    """Run a workflow: a declared YAML DAG (each node its own Execution) or a file."""
    target = args.workflow
    ws_root = find_workspace_root() or os.path.abspath(".")
    cfg = load_config(os.path.join(ws_root, ".compart", "config.yaml"))

    wf = cfg.workflows.get(target)
    if wf:
        _run_declared_workflow(ws_root, wf, cfg)
        return

    if target.endswith((".yaml", ".yml")) and os.path.exists(target):
        with open(target, encoding="utf-8") as f:
            wdata = yaml.safe_load(f) or {}
        wname = wdata.get("name") or os.path.splitext(os.path.basename(target))[0]
        nodes = []
        if "steps" in wdata and isinstance(wdata["steps"], list):
            for sdata in wdata["steps"]:
                if isinstance(sdata, dict):
                    nodes.append(WorkflowNodeConfig(
                        name=sdata.get("name") or f"step_{len(nodes)+1}",
                        type=sdata.get("type", "process"),
                        command=sdata.get("command", ""),
                        compartment=sdata.get("compartment", "default"),
                        depends_on=sdata.get("depends_on") or [],
                    ))
        wf = WorkflowConfig(name=wname, nodes=nodes)
        _run_declared_workflow(ws_root, wf, cfg)
        return

    if os.path.exists(target):
        compartment_id = getattr(args, "compartment", "default") or "default"
        _run_workflow_file(ws_root, target, compartment_id, getattr(args, "verbose", False))
        return

    print(
        f"Error: Workflow '{target}' not found. "
        f"Available workflows: {sorted(cfg.workflows) or 'none'}"
    )
    sys.exit(1)


def cmd_diff(args):
    """Show change sets associated with agent executions (the review surface)."""
    ws_root = find_workspace_root()
    if not ws_root:
        print("Error: Not inside a Compart workspace. Run 'compart init' first.")
        sys.exit(1)

    exec_mgr = ExecutionManager(workdir=ws_root)

    if args.execution:
        ex = exec_mgr.get(args.execution)
        if ex is None:
            print(f"Error: Execution '{args.execution}' not found.")
            sys.exit(1)
        records = [ex]
    else:
        records = [ex for ex in exec_mgr.list_all() if ex.changes]
        if args.unapplied:
            records = [ex for ex in records if ex.status != ExecutionStatus.APPLIED]
        records.sort(key=lambda e: e.finished_at or 0, reverse=True)

    if args.json:
        _print_json({
            "change_sets": len(records),
            "total_changes": sum(len(ex.changes) for ex in records),
            "executions": [
                {**ex.to_dict(), "git_trailers": ex.git_trailers()}
                for ex in records
            ],
        })
        return

    print("\nCOMPART DIFF - changes associated with agent executions\n")
    if not records:
        print("  (no change sets recorded - run an agent under Compart first)")
        print()
        return

    total = 0
    for ex in records:
        total += len(ex.changes)
        dur = f"{ex.duration_s:.0f}s" if ex.duration_s else "?"
        print(f"# {ex.execution_id:<14} {ex.agent_name:<12} {ex.compartment_id:<12} {ex.status:<10} {len(ex.changes)} change(s)  ({dur})")
        for chg in ex.changes:
            print(f"    {chg.get('status', 'modified').upper():<9} {chg.get('path', '')}")
        if getattr(args, "trailers", False):
            print("  Git Trailers:")
            for line in ex.git_trailers().splitlines():
                print(f"    {line}")
        print()
    print(f"{len(records)} change set(s), {total} file change(s) total")
    print()


def _git_commit_execution(
    ws_root: str,
    ex: Execution,
    user_message: Optional[str] = None,
) -> bool:
    """Stage an execution's changed files and create a Git commit with RFC-5322 metadata trailers."""
    if not shutil.which("git"):
        print("  Error: 'git' command not found in PATH.")
        return False

    res = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=ws_root,
        capture_output=True,
        text=True,
    )
    if res.returncode != 0:
        print("  Error: Not inside a Git repository. Cannot create Git commit.")
        return False

    paths = [c.get("path") for c in ex.changes if c.get("path")]
    if not paths:
        print(f"  # {ex.execution_id}: no changed files to stage.")
        return False

    stage_res = subprocess.run(
        ["git", "add", "--"] + paths,
        cwd=ws_root,
        capture_output=True,
        text=True,
    )
    if stage_res.returncode != 0:
        print(f"  Error staging files with git: {stage_res.stderr.strip()}")
        return False

    msg_header = user_message or f"Compart: apply changes from {ex.agent_name} ({ex.execution_id})"
    full_commit_msg = f"{msg_header}\n\n{ex.git_trailers()}\n"

    commit_res = subprocess.run(
        ["git", "commit", "-m", full_commit_msg],
        cwd=ws_root,
        capture_output=True,
        text=True,
    )
    if commit_res.returncode != 0:
        print(f"  Git commit failed: {commit_res.stderr.strip() or commit_res.stdout.strip()}")
        return False

    print(f"  # {ex.execution_id}: committed to Git with metadata trailers.")
    return True


def _apply_execution(exec_mgr: ExecutionManager, ex: Execution, force: bool = False) -> bool:
    """Promote one execution's change set; surface conflicts with other work."""
    if not ex.changes:
        print(f"  # {ex.execution_id}: no changes to apply.")
        return False
    if ex.status == ExecutionStatus.APPLIED:
        print(f"  # {ex.execution_id}: already applied.")
        return False

    paths = {c.get("path", "") for c in ex.changes}
    conflicts = []
    for other in exec_mgr.list_all():
        if other.execution_id == ex.execution_id or other.status == ExecutionStatus.APPLIED:
            continue
        overlap = paths & {c.get("path", "") for c in other.changes}
        for p in sorted(overlap):
            conflicts.append((other.execution_id, p))

    if conflicts and not force:
        print(f"  # {ex.execution_id}: CONFLICT - changes overlap other un-applied executions:")
        for other_id, path in conflicts:
            print(f"      {path}  (also modified by {other_id})")
        print("      Use --force to apply anyway.")
        return False

    ex.apply()
    exec_mgr.save(ex)
    print(f"  # {ex.execution_id}: applied {len(ex.changes)} change(s).")
    return True


def cmd_apply(args):
    """Promote selected change sets into the workspace baseline, with optional Git commit."""
    ws_root = find_workspace_root()
    if not ws_root:
        print("Error: Not inside a Compart workspace. Run 'compart init' first.")
        sys.exit(1)

    exec_mgr = ExecutionManager(workdir=ws_root)
    if args.execution:
        ex = exec_mgr.get(args.execution)
        if ex is None:
            print(f"Error: Execution '{args.execution}' not found.")
            sys.exit(1)
        targets = [ex]
    else:
        targets = [
            e for e in exec_mgr.list_all()
            if e.changes and e.status == ExecutionStatus.COMPLETED
        ]
        if not targets:
            print("Nothing to apply: no completed executions with recorded changes.")
            return

    applied_targets = [ex for ex in targets if _apply_execution(exec_mgr, ex, force=args.force)]
    print(f"\nApplied {len(applied_targets)} change set(s).")

    if getattr(args, "commit", False):
        print("\nCreating Git commit(s) with Compart metadata trailers...")
        for ex in applied_targets:
            _git_commit_execution(ws_root, ex, user_message=getattr(args, "message", None))

    sys.exit(0 if applied_targets else 1)


def cmd_commit(args):
    """Stage and commit applied execution change sets to Git with RFC-5322 metadata trailers."""
    ws_root = find_workspace_root()
    if not ws_root:
        print("Error: Not inside a Compart workspace. Run 'compart init' first.")
        sys.exit(1)

    exec_mgr = ExecutionManager(workdir=ws_root)
    if args.execution:
        ex = exec_mgr.get(args.execution)
        if ex is None:
            print(f"Error: Execution '{args.execution}' not found.")
            sys.exit(1)
        targets = [ex]
    else:
        targets = [
            e for e in exec_mgr.list_all()
            if e.changes and e.status in (ExecutionStatus.APPLIED, ExecutionStatus.COMPLETED)
        ]
        if not targets:
            print("Nothing to commit: no completed or applied executions with changes.")
            return
        if not getattr(args, "all", False):
            targets = [max(targets, key=lambda e: e.finished_at or 0)]

    committed = 0
    for ex in targets:
        if ex.status != ExecutionStatus.APPLIED:
            if not _apply_execution(exec_mgr, ex, force=getattr(args, "force", False)):
                continue
        if _git_commit_execution(ws_root, ex, user_message=getattr(args, "message", None)):
            committed += 1

    print(f"\nCommitted {committed} execution change set(s) to Git.")
    sys.exit(0 if committed else 1)


def cmd_undo(args):
    """Reverse the last Compart-managed apply operation and restore the worktree."""
    ws_root = find_workspace_root()
    if not ws_root:
        print("Error: Not inside a Compart workspace. Run 'compart init' first.")
        sys.exit(1)

    exec_mgr = ExecutionManager(workdir=ws_root)
    if args.execution:
        ex = exec_mgr.get(args.execution)
        if ex is None:
            print(f"Error: Execution '{args.execution}' not found.")
            sys.exit(1)
        targets = [ex]
    else:
        applied = [e for e in exec_mgr.list_all() if e.status == ExecutionStatus.APPLIED]
        if not applied:
            print("Nothing to undo: no applied change sets.")
            return
        targets = [max(applied, key=lambda e: e.finished_at or 0)]

    for ex in targets:
        if ex.status != ExecutionStatus.APPLIED:
            print(f"  # {ex.execution_id}: not applied - nothing to undo.")
            sys.exit(1)

        snap_dir = ex.snapshot_dir
        if snap_dir and os.path.isdir(snap_dir):
            restored = SnapshotManager(workdir=ws_root, snapshot_dir=snap_dir).restore()
            print(f"  # {ex.execution_id}: restored {restored} file(s) from pre-execution snapshot.")
        else:
            print(
                f"  # {ex.execution_id}: no snapshot found - "
                "bookkeeping reversed but files NOT restored on disk."
            )

        ex.status = ExecutionStatus.COMPLETED
        ex.emit("execution.unapplied", {"files_restored": bool(snap_dir and os.path.isdir(snap_dir))})
        exec_mgr.save(ex)
        print(f"  # {ex.execution_id}: {len(ex.changes)} change(s) returned to pending.")



def cmd_restore(args):
    """Restore the workspace from a session's snapshot checkpoint."""
    ws_root = find_workspace_root()
    if not ws_root:
        print("Error: Not inside a Compart workspace. Run 'compart init' first.")
        sys.exit(1)

    sess_mgr = SessionManager(workdir=ws_root)
    session = sess_mgr.get_session(args.session_id)
    if session is None:
        print(f"Error: Session '{args.session_id}' not found.")
        sys.exit(1)

    snap_dir = None
    for cp in reversed(session.checkpoints):
        manifest = cp.get("snapshot_manifest")
        if manifest and os.path.isdir(manifest):
            snap_dir = manifest
            break
    if not snap_dir:
        print(f"Error: Session '{args.session_id}' has no snapshot checkpoint to restore.")
        sys.exit(1)

    SnapshotManager(workdir=ws_root, snapshot_dir=snap_dir).restore()
    print(f"Workspace restored to the checkpoint for session '{args.session_id}'.")



def main():
    # Direct agent shortcut: `compart claude` / `compart opencode` / `compart codex`
    if len(sys.argv) > 1 and sys.argv[1] in _KNOWN_AGENTS:
        agent_name = sys.argv[1]
        user_argv = sys.argv[2:]
        ws_root = find_workspace_root() or os.path.abspath(".")
        sys.exit(_launch_agent(agent_name, ws_root, user_argv=user_argv))

    description = textwrap.dedent("""\
        Compart: the audit layer for AI coding agents

        Workspace:
          compart init                     Initialize a Compart workspace
          compart status                   Show workspace health & active executions
          compart inspect                  Dump declared compartments & policies

        Agents:
          compart claude | opencode | codex | cursor | aider
                                           Run coding agent in governed OS sandbox
          compart exec -- <cmd>            Run arbitrary command inside a compartment

        Workflows:
          compart -w <name>                Create a new workflow branch
          compart step <workflow> <target> Add a step with auto-inferred properties
          compart --run <workflow>         Execute declared workflow DAG

        Changes:
          compart diff                     Review change sets attributed by agent
          compart apply                    Promote changes to workspace baseline
          compart commit -m <msg>          Commit to Git with RFC-5322 metadata trailers
          compart undo                     Instant physical snapshot rollback
          compart restore                  Restore from session checkpoint
    """)

    parser = argparse.ArgumentParser(
        description=description,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-w", "--workflow",
        dest="workflow_flag",
        default=None,
        help="Create a new workflow branch (e.g. compart -w invoice-pipeline)",
    )
    parser.add_argument(
        "--run",
        dest="run_flag",
        default=None,
        help="Run a workflow DAG directly (e.g. compart --run invoice-pipeline)",
    )
    subparsers = parser.add_subparsers(dest="command", help=argparse.SUPPRESS)

    subparsers.add_parser("init", help="Initialize a Compart workspace in the current directory")

    subparsers.add_parser("status", help="Show workspace status: agents, lanes, security events")

    inspect_parser = subparsers.add_parser("inspect", help="Dump declarative topology and project state")
    inspect_parser.add_argument("--json", action="store_true")

    comp_parser = subparsers.add_parser("compartment", help=argparse.SUPPRESS)
    comp_subparsers = comp_parser.add_subparsers(dest="compartment_command")
    comp_create_parser = comp_subparsers.add_parser("create")
    comp_create_parser.add_argument("name")

    connect_parser = subparsers.add_parser("connect", help=argparse.SUPPRESS)
    connect_parser.add_argument("source")
    connect_parser.add_argument("target")

    run_parser = subparsers.add_parser("run", help="Run a declared workflow DAG (alias for --run)")
    run_parser.add_argument("target", nargs="?", default=None, help="Workflow name (e.g. invoice-pipeline), workflow file, or command")
    run_parser.add_argument("--compartment", default="default", help="Compartment policy for a standalone file")
    run_parser.add_argument("--verbose", action="store_true")

    diff_parser = subparsers.add_parser("diff", help="Show change sets associated with agent executions")
    diff_parser.add_argument("--execution", default=None, help="Show changes for a single execution")
    diff_parser.add_argument("--unapplied", action="store_true", help="Only show change sets not yet applied")
    diff_parser.add_argument("--trailers", action="store_true", help="Include formatted Git metadata trailers")
    diff_parser.add_argument("--json", action="store_true")

    apply_parser = subparsers.add_parser("apply", help="Promote change sets into the workspace baseline")
    apply_parser.add_argument("--execution", default=None, help="Apply a single execution's change set")
    apply_parser.add_argument("--force", action="store_true", help="Apply even when changes overlap other executions")
    apply_parser.add_argument("-c", "--commit", action="store_true", help="Automatically create a Git commit with Compart trailers")
    apply_parser.add_argument("-m", "--message", default=None, help="Custom Git commit message")

    commit_parser = subparsers.add_parser("commit", help="Commit applied execution changes to Git with RFC-5322 metadata trailers")
    commit_parser.add_argument("-m", "--message", default=None, help="Custom Git commit message header")
    commit_parser.add_argument("--execution", default=None, help="Commit a specific execution's change set")
    commit_parser.add_argument("--all", action="store_true", help="Commit all completed/applied executions")
    commit_parser.add_argument("--force", action="store_true", help="Apply and commit even if changes overlap")

    undo_parser = subparsers.add_parser("undo", help="Reverse the last Compart-managed apply operation")
    undo_parser.add_argument("--execution", default=None, help="Undo a specific execution's apply")

    restore_parser = subparsers.add_parser("restore", help="Restore the workspace from a session's snapshot checkpoint")
    restore_parser.add_argument("session_id", nargs="?", default=None, help="Session ID to restore (defaults to latest)")

    exec_parser = subparsers.add_parser("exec", help="Run a command or launch an agent inside an explicitly selected compartment")
    exec_parser.add_argument("--compartment", default=None, help="Override the compartment for this execution")
    exec_parser.add_argument("cmd", nargs=argparse.REMAINDER)

    wrap_parser = subparsers.add_parser("wrap", help=argparse.SUPPRESS)
    wrap_parser.add_argument("-c", "--claude", nargs="?", const="")
    wrap_parser.add_argument("-o", "--opencode", nargs="?", const="")
    wrap_parser.add_argument("--lane", default="default")
    wrap_parser.add_argument("--agent", default="Claude Code")
    wrap_parser.add_argument("--task", default="")
    wrap_parser.add_argument("--verbose", action="store_true")
    wrap_parser.add_argument("cmd", nargs=argparse.REMAINDER)

    lane_parser = subparsers.add_parser("lane", help=argparse.SUPPRESS)
    lane_subparsers = lane_parser.add_subparsers(dest="lane_command")
    lane_create_p = lane_subparsers.add_parser("create")
    lane_create_p.add_argument("name")
    lane_create_p.add_argument("--agent", default="Claude Code")
    lane_inspect_p = lane_subparsers.add_parser("inspect")
    lane_inspect_p.add_argument("name")
    lane_inspect_p.add_argument("--json", action="store_true")

    subparsers.add_parser("lanes", help=argparse.SUPPRESS)

    integ_parser = subparsers.add_parser("integrate", help=argparse.SUPPRESS)
    integ_subparsers = integ_parser.add_subparsers(dest="subcommand")
    integ_create = integ_subparsers.add_parser("create")
    integ_create.add_argument("lanes", nargs="+")
    integ_subparsers.add_parser("preview")
    integ_subparsers.add_parser("apply")

    subparsers.add_parser("sessions", help=argparse.SUPPRESS)

    session_parser = subparsers.add_parser("session", help=argparse.SUPPRESS)
    session_subparsers = session_parser.add_subparsers(dest="session_command")
    sess_inspect_p = session_subparsers.add_parser("inspect")
    sess_inspect_p.add_argument("session_id")
    sess_inspect_p.add_argument("--json", action="store_true")
    sess_rollback_p = session_subparsers.add_parser("rollback")
    sess_rollback_p.add_argument("session_id")

    branch_parser = subparsers.add_parser("branch", help="Create a new workflow branch in workflows/<name>.yaml")
    branch_parser.add_argument("name", help="Workflow branch name")

    step_parser = subparsers.add_parser("step", help="Add a step to a workflow branch with auto-inferred properties")
    step_parser.add_argument("workflow", help="Workflow name (workflows/<workflow>.yaml)")
    step_parser.add_argument("target", help="Script file path (e.g. src/ocr.py) or command (e.g. pytest -q)")
    step_parser.add_argument("--name", default=None, help="Custom step name (inferred from filename by default)")
    step_parser.add_argument("--compartment", default=None, help="Compartment policy (research, builder, network, tester, default)")
    step_parser.add_argument("--type", default=None, choices=["process", "agent"], help="Step type")
    step_parser.add_argument("--depends-on", default=None, help="Comma-separated prerequisite step names")

    workflow_parser = subparsers.add_parser("workflow", help="Manage and run agentic workflow branches")
    workflow_subparsers = workflow_parser.add_subparsers(dest="workflow_command")
    wf_run_p = workflow_subparsers.add_parser("run", help="Run a declared YAML workflow DAG (each node its own Execution) or a workflow file")
    wf_run_p.add_argument("workflow", help="Declared workflow name from config.yaml, or a workflow file path")
    wf_run_p.add_argument("--compartment", default="default", help="Compartment for a standalone workflow file")
    wf_run_p.add_argument("--verbose", action="store_true")

    for alias in ("branch", "new", "create"):
        wf_b_p = workflow_subparsers.add_parser(alias, help="Create a new workflow branch")
        wf_b_p.add_argument("name", help="Workflow branch name")

    wf_step_p = workflow_subparsers.add_parser("step", help="Add a step to a workflow branch")
    wf_step_p.add_argument("workflow", help="Workflow name")
    wf_step_p.add_argument("target", help="Script file path or shell command")
    wf_step_p.add_argument("--name", default=None, help="Custom step name")
    wf_step_p.add_argument("--compartment", default=None, help="Compartment policy")
    wf_step_p.add_argument("--type", default=None, choices=["process", "agent"], help="Step type")
    wf_step_p.add_argument("--depends-on", default=None, help="Comma-separated dependencies")

    for alias in ("show", "inspect", "info", "list"):
        wf_s_p = workflow_subparsers.add_parser(alias, help="Inspect declared workflow steps and DAG")
        wf_s_p.add_argument("name", nargs="?", default=None, help="Workflow name")

    shim_parser = subparsers.add_parser("_exec_shim", help=argparse.SUPPRESS)
    shim_parser.add_argument("shim_args", nargs=argparse.REMAINDER)

    args = parser.parse_args()

    if getattr(args, "run_flag", None):
        cmd_run(argparse.Namespace(target=args.run_flag, compartment="default", verbose=False))
        return

    if getattr(args, "workflow_flag", None):
        cmd_workflow_branch(argparse.Namespace(name=args.workflow_flag))
        return

    dispatch = {
        "init": cmd_init,
        "status": cmd_status,
        "inspect": cmd_inspect,
        "run": cmd_run,
        "lanes": cmd_lanes,
        "sessions": cmd_sessions,
        "diff": cmd_diff,
        "apply": cmd_apply,
        "commit": cmd_commit,
        "undo": cmd_undo,
        "restore": cmd_restore,
        "branch": cmd_workflow_branch,
        "step": cmd_step,
    }

    if args.command in dispatch:
        dispatch[args.command](args)
    elif args.command == "exec":
        if args.cmd and args.cmd[0] == "--":
            args.cmd = args.cmd[1:]
        cmd_exec(args)
    elif args.command == "wrap":
        if args.cmd and args.cmd[0] == "--":
            args.cmd = args.cmd[1:]
        cmd_wrap(args)
    elif args.command == "lane":
        lcmd = getattr(args, "lane_command", None)
        if lcmd == "create":
            cmd_lane_create(args)
        elif lcmd == "inspect":
            cmd_lane_inspect(args)
        else:
            lane_parser.print_help()
    elif args.command == "integrate":
        cmd_integrate(args)
    elif args.command == "session":
        scmd = getattr(args, "session_command", None)
        if scmd == "inspect":
            cmd_session_inspect(args)
        elif scmd == "rollback":
            cmd_session_rollback(args)
        else:
            session_parser.print_help()
    elif args.command == "compartment":
        if getattr(args, "compartment_command", None) == "create":
            cmd_compartment_create(args)
        else:
            comp_parser.print_help()
    elif args.command == "connect":
        cmd_connect(args)
    elif args.command == "workflow":
        wcmd = getattr(args, "workflow_command", None)
        if wcmd == "run":
            cmd_workflow_run(args)
        elif wcmd in ("branch", "new", "create"):
            cmd_workflow_branch(args)
        elif wcmd == "step":
            cmd_step(args)
        elif wcmd in ("show", "inspect", "info", "list"):
            cmd_workflow_show(args)
        else:
            workflow_parser.print_help()
    elif args.command == "_exec_shim":
        cmd_exec_shim(args)
    else:
        parser.print_help()


def cli():
    main()


if __name__ == "__main__":
    cli()
